# name: Waka Readme

# on:
#   # for manual workflow trigger
#   workflow_dispatch:
#   schedule:
#     # runs at 12 AM UTC (5:30 AM IST)
#     - cron: "0 0 * * *"

# jobs:
#   update-readme:
#     name: WakaReadme DevMetrics
#     runs-on: ubuntu-latest
#     steps:
#       - uses: athul/waka-readme@master # this action name
#         with:
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

name: Waka Readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # - cron: "0 0 * * *" # once a day
    - cron: "17 13 * * 2" # “At 13:17 on Tuesday.” - next @  at 2024-03-26 13:17:00

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout Repository
      #   uses: actions/checkout@v2

      # - name: Set up Node.js 20
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '20'
      #     cache: 'npm'

      # - name: Install dependencies
      #   run: npm install

      - name: Update WakaReadme Stats
        uses: athul/waka-readme@master # do NOT replace with anything else
        with:
          # GH_TOKEN: ${{ secrets.GH_TOKEN }} # optional if on profile readme
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
          ### meta
          API_BASE_URL: https://wakatime.com/api # optional
          # REPOSITORY: YOUR_GITHUB_USERNAME/YOUR_REPOSITORY_NAME # optional
          ### content
          SHOW_TITLE: true # optional
          SECTION_NAME: waka # optional
          BLOCKS: -> # optional
          CODE_LANG: rust # optional
          TIME_RANGE: all_time # optional
          LANG_COUNT: 10 # optional
          SHOW_TIME: true # optional
          SHOW_TOTAL: true # optional
          SHOW_MASKED_TIME: false # optional
          STOP_AT_OTHER: true # optional
          IGNORED_LANGUAGES: YAML TOML # optional - JSON
          ### commit
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics # optional
          TARGET_BRANCH: main # optional
          TARGET_PATH: README.md # optional
          COMMITTER_NAME: GitHubActionBot # optional
          COMMITTER_EMAIL: action-bot@github.com # optional
          AUTHOR_NAME: Akbarsha # optional
          AUTHOR_EMAIL: ${{ secrets.MY_EMAIL }}, # optional
          # you can populate email-id with secretes instead
      - name: Update WakaReadme Stats (Two)
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: waka_two
          SHOW_OS: true
          SHOW_LANGUAGE: true
          SHOW_PROJECTS: true
          SHOW_LOC_CHART: true