# name: Waka Readme

# on:
#   # for manual workflow trigger
#   workflow_dispatch:
#   schedule:
#     # runs at 12 AM UTC (5:30 AM IST)
#     - cron: "0 0 * * *"

# jobs:
#   update-readme:
#     name: WakaReadme DevMetrics
#     runs-on: ubuntu-latest
#     steps:
#       - uses: athul/waka-readme@master # this action name
#         with:
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

name: Waka Readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST) “At minute 45.” at 2024-02-03 12:45:00
    # - cron: "0 * * * *" # “At minute 0.” at 2024-02-03 13:00:00   
    - cron: "1 * * * *" # “At minute 1.” at 2024-02-04 12:01:00
    # - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
        # this action name
      # - uses: iamakbarsha1/waka-readme-stats@main
      - uses: athul/waka-readme@master # do NOT replace with anything else
        with:
          # GH_TOKEN: ${{ secrets.GH_TOKEN }} # optional if on profile readme
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
          ### meta
          API_BASE_URL: https://wakatime.com/api # optional
          # REPOSITORY: YOUR_GITHUB_USERNAME/YOUR_REPOSITORY_NAME # optional
          ### content
          SHOW_TITLE: true # optional
          SECTION_NAME: waka # optional
          BLOCKS: -> # optional
          CODE_LANG: rust # optional
          TIME_RANGE: all_time # optional
          LANG_COUNT: 10 # optional
          SHOW_TIME: true # optional
          SHOW_TOTAL: true # optional
          SHOW_MASKED_TIME: false # optional
          STOP_AT_OTHER: true # optional
          IGNORED_LANGUAGES: YAML TOML # optional - JSON
          # EXTRAS
          SHOW_OS: true
          SHOW_LANGUAGE: true
          SHOW_PROJECTS: true
          SHOW_LOC_CHART: true
          ### commit
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics # optional
          TARGET_BRANCH: main # optional
          TARGET_PATH: README.md # optional
          COMMITTER_NAME: GitHubActionBot # optional
          COMMITTER_EMAIL: action-bot@github.com # optional
          AUTHOR_NAME: Akbarsha # optional
          AUTHOR_EMAIL: ${{ secrets.MY_EMAIL }} # optional
          # you can populate email-id with secretes instead